modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"
[[mods]]
modId = "dungeon_quest"
version = "${file.jarVersion}"
displayName = "DungeonQuest"
description = '''

'''
[[dependencies.dungeon_quest]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.dungeon_quest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.18.2)"
ordering = "NONE"
side = "BOTH"
